### ISSUE TITLE
使用多级包路径加载xml文件时包 系统找不到指定的路径

### ISSUE THREAD

**Issue by canmengqian** [ralgond/mybatis-py#1]
当使用 ”app.learn_site.mapper“ 多级包路径时报错
![image](https://github.com/user-attachments/assets/52d809a0-e8e7-4b67-84ac-ed077bc11e04)

**Comment by ralgond** [comment]
您好，mapper_path是个文件夹路径，该文件夹下放置所有您需要的xml文件，可以是相对路径，也可以是绝对路径
